file(GLOB_RECURSE ALL_SOURCES *.c *.cpp)
file(GLOB_RECURSE ALL_HEADERS *.h *.hpp)

list(FILTER ALL_SOURCES EXCLUDE REGEX ${CMAKE_BINARY_DIR})
list(FILTER ALL_HEADERS EXCLUDE REGEX ${CMAKE_BINARY_DIR})
list(FILTER ALL_HEADERS EXCLUDE REGEX ${CMAKE_SOURCE_DIR}/QCustomPlot)
list(FILTER ALL_SOURCES EXCLUDE REGEX ${CMAKE_SOURCE_DIR}/QCustomPlot)

message(STATUS "All sources collected")